### ISSUE TITLE
Patch Loss usage

### ISSUE THREAD

**Issue by usamashami11** [Suanmd/Patch-Loss-for-Super-Resolution#1]
Hello, I am trying to train **ESRGAN** on my **custom dataset** and **Scale 6**, and I want to use **Patch Loss**, but the issue is that option is already commented out in this .yml file. i.e. `options/train/ESRGAN/train_ESRGAN_x4_0.yml` 

- Do I have to un-comment this `patch_opt` section to use patch loss along with other losses?
https://github.com/Suanmd/Patch-Loss-for-Super-Resolution/blob/4b2f3e58a26330d076d5bfbccda9d191817d64a0/options/train/ESRGAN/train_ESRGAN_x4_0.yml#L103C1-L103C15

- Moreover, referring to the following **TEXT** from paper (highlighted below), kindly tell me where should I update the **Weight** for Patch Loss in the **CODE** below? (I have computed the kernels sizes for p and q according to my scale i.e. 6, though)

1. `perceptual_patch_weight` in `perceptual_opt`?  https://github.com/Suanmd/Patch-Loss-for-Super-Resolution/blob/4b2f3e58a26330d076d5bfbccda9d191817d64a0/options/train/ESRGAN/train_ESRGAN_x4_0.yml#L100

2. `loss_weight` in `patch_opt`? https://github.com/Suanmd/Patch-Loss-for-Super-Resolution/blob/4b2f3e58a26330d076d5bfbccda9d191817d64a0/options/train/ESRGAN/train_ESRGAN_x4_0.yml#L107 

3. Both 1 and 2 (with same value)?

------
TEXT:
------
_For GAN-based methods, the **weights** of **perceptual loss**, **L1 loss**, and **adversarial loss** are set to 1.0, 0.01, and 0.005, respectively_
_For 4x scaling, the **weight** of **patch loss** for SRGAN and ESRGAN is set to **0.1**, the parameters (p1, p2, p3) = (7, 11, 15), (q1, q2) = (8, 16), and **κ = 0.1**.
The values of p and q should match the scale factor α. In our experiment, p1, p2 and p3 are set to 2α−1, 3α−1 and 4α−1, respectively, while q1, q2 and q3 are matched to the sizes of the feature maps_

-------
CODE:
-------
```
-------------------------------------------------
train_ESRGAN_x4_0.yml (modified for scale 6)
-------------------------------------------------
# losses
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1e-2
    reduction: mean

  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv5_4': 1  # before relu
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 1.0
    style_weight: 0
    criterion: patch
    use_std_to_force: false
    perceptual_patch_weight: 0.0
    # perceptual_kernels: [4, 8] # (for scale = 4)
    perceptual_kernels: [6, 12]  # (for scale = 6)

  patch_opt:
    type: patchLoss3DXD
    use_std_to_force: false
    # kernel_sizes: [7, 11, 15] # (for alpha/scale = 4)
    kernel_sizes: [11, 17, 23] # (for alpha/scale = 6)
    loss_weight: 1.0

  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 5e-3
```

  Kindly assist me and answer the queries, since there is a lot of confusion. Thanks!
